#cloud-config
# Upgrade system and install OpenVPN package
package_update: true
package_upgrade: true
packages:
  - openvpn
runcmd:
  # Allow IP Forwarding, configure UFW
  - sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
  - sysctl -p
  - ufw allow ssh
  - ufw allow 1194/udp
  # Add static routes with netplan
  - sed -i '$a\    enp7s0;\n      dhcp4; true\n      routes;\n        - to; 10.8.2.0/24\n          via; 10.0.0.1\n        - to; 10.8.3.0/24\n          via; 10.0.0.1\n        - to; 10.8.4.0/24\n          via; 10.0.0.1\n        - to; 10.8.5.0/24\n          via; 10.0.0.1' /etc/netplan/50-cloud-init.yaml
  - sed -i 's/;/:/g' /etc/netplan/50-cloud-init.yaml
  - netplan generate
  - netplan apply
  # Adjust UFW rules to masquerade client connections
  - sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/' /etc/default/ufw
  - sed -i '1i# START OPENVPN RULES\n# NAT table rules\n*nat\n:POSTROUTING ACCEPT [0:0]\n# Allow traffic from OpenVPN client to eth0\n-A POSTROUTING -s 10.8.0.0/8 -d 10.0.0.0/24 -j RETURN\n-A POSTROUTING -s 10.8.0.0/8 -o eth0 -j MASQUERADE\nCOMMIT\n# END OPENVPN RULES\n' /etc/ufw/before.rules
  - ufw --force enable
  # Start OpenVPN service
  - systemctl start openvpn@server
  - systemctl enable openvpn@server
write_files:
  # Create OpenVPN server configuration
  - path: /etc/openvpn/server.conf
    content: |
      port 1194
      proto udp
      dev tun
      ca ca.crt
      cert server.crt
      key server.key
      dh dh2048.pem
      tls-auth ta.key 0
      topology subnet
      server 10.8.X.0 255.255.255.0
      ifconfig-pool-persist /var/log/openvpn/ipp.txt
      push "route 10.0.0.0 255.255.255.0"
      push "redirect-gateway def1 bypass-dhcp"
      push "dhcp-option DNS 208.67.222.222"
      push "dhcp-option DNS 208.67.220.220"
      keepalive 10 120
      user nobody
      group nogroup
      persist-key
      persist-tun
      status /var/log/openvpn/openvpn-status.log
      verb 3
      explicit-exit-notify 1
      data-ciphers AES-256-GCM:AES-128-GCM:AES-256-CBC
  # Import necessary certificates and keys (from existing PKI)
  - path: /etc/openvpn/ca.crt
    encoding: b64
    content: <sensitive>
  - path: /etc/openvpn/server.crt
    encoding: b64
    content: <sensitive>
  - path: /etc/openvpn/server.key
    encoding: b64
    content: <sensitive>
  - path: /etc/openvpn/dh2048.pem
    encoding: b64
    content: <sensitive>
  - path: /etc/openvpn/ta.key
    encoding: b64
    content: <sensitive>